version: "2"
services:
  app:
    container_name: app1
    restart: always
    build: .
    ports:
      - "9001:9001"
  #   links:
  #     - mongo
  # mongo:
  #   container_name: mongo
  #   image: mongo:latest
  #   volumes:
  #     - ./data:/data/db
  #   ports:
  #     - "27017:27017"